config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"
  mount ActionCable.server => "/cable"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :rooms, only: [:new, :create, :show, :update, :index] do
    resources :tracks, only: [:create]
    resources :messages, only: [:create]
  end

  get "*username/*room_slug", to: "rooms#show", as: :custom_room
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :tracks, dependent: :destroy
  has_many :messages, dependent: :destroy
  validates :title, :description, :custom_message, presence: true
  after_create :generate_slug

  private

  def generate_slug
    self.slug = title.parameterize
    self.save
  end
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :messages
  has_attachment :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  after_filter :store_action

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end

  def store_action
    return unless request.get?
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        !request.xhr?) # don't store ajax calls
      store_location_for(:user, request.fullpath)
    end
  end

  def default_url_options
  { host: ENV["HOST"] || "localhost:3000" }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = Message.new(params_message)
    @room = Room.find(params[:room_id])
    @message.room = @room
    @message.user = current_user
    if @message.save
      # redirect_to room_path(@room)
      ActionCable.server.broadcast("room_#{@room.id}", {
        message_partial: render(partial: "message", locals: { message: @message }),
        current_user_id: current_user.id
      })
      head :ok
    else
      render "rooms/show"
    end
  end

  private

  def params_message
    params.require(:message).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
skip_before_action :authenticate_user!, only: :show

  def index
    @rooms = Room.where(user_id: current_user.id)
  end

  def show
    if params[:room_slug]
      user = User.find_by_email('meryl@gmail.com') # WARNING: this works only for Meryl => need to add twitter nickname or facebook nickname into users table
      @room = user.rooms.find_by_slug(params[:room_slug])
    else
      @room = Room.find(params[:id])
    end
    @tracks = @room.tracks.all
    @message = Message.new
    # @messages = @room.messages.last(3)
    @messages = @room.messages
  end

  def new
    @room = Room.new
    @track = Track.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_path(@room)
    else
      render :new
    end
  end

  def update
    @room = Room.find(params[:id])
    # @room.current_track = room_params["current_track"].split("v=")[-1].split("&")[0]
    #room_params[:current_track] = room_params[:current_track].split("v=")[-1].split("&")[0]
    current_track = room_params[:current_track].split("v=")[-1].split("&")[0]
    @room.current_track_time = room_params[:current_track_time]
    @room.current_track = current_track
    current_track_title = room_params[:current_track_title].gsub("&", ' ').gsub("'", ' ')
    @room.current_track_title = current_track_title
    @room.save
    # @room.update(room_params)
    head :ok
  end

  private

  def room_params
    params.require(:room).permit(:title, :decription, :custom_message, :photo_url, :current_track, :current_track_time, :current_track_title)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
skip_before_action :authenticate_user!, only: :index

  def create
    @track = Track.new(track_params)
    @room = Room.find(params[:room_id])
    @track.room = @room
    if @track.save
      redirect_to room_path(@room)
    else
      render "rooms/show"
    end
  end

  private

  def track_params
    params.require(:track).permit(:title, :artist, :youtubeid)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def yield_with_default(holder, default)
    if content_for?(holder)
      content_for(holder).squish
    else
      default
    end
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title><%= meta_title %></title>

    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="shortcut icon" type="image/x-icon" href= <%= image_path "favicon.ico" %>
    <meta name="description" content="Weesound, the reference live service for influencers. Let your fans chat with you and listen to your music in live">
  </head>
  <body id="<%= yield (:body_id) %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>

  </body>
</html>

app/views/messages/_message.html.erb
<% if message.user == @room.user %>
  <div class="message-influenceur">
    <div class= "container-user-photo">
      <% if user_signed_in = true %>
      <% userphoto = message.user.facebook_picture_url || message.user.photo.try(:path) || 'v1503931725/anonyme_dumce2.jpg' %>
      <%= cl_image_tag userphoto, class: "user-photo"  %>
      <% end %>
    </div>
    <div class="message-content"><div class="username"><%= message.user.username %></div><%= message.content %></div>
  </div>
<% else %>
  <div class="message">
    <div class= "container-user-photo">
      <% if user_signed_in = true %>
        <% userphoto = message.user.facebook_picture_url || message.user.photo.try(:path) || 'v1503931725/anonyme_dumce2.jpg' %>
        <%= cl_image_tag userphoto, class: "user-photo"  %>
      <% end %>
    </div>
    <div class="message-content"><div class="username"><%= message.user.username %></div><%= message.content %></div>
  </div>
<% end %>

app/views/pages/home.html.erb
<div class="player_background">
  <!-- <img src="https://slack-imgs.com//mc?c=1&url=https%3A%2F%2Fscontent-iad3-1.cdninstagram.com%2Ft51.2885-15%2Fe35%2F20589379_2000039293551612_5999224329236119552_n.jpg" alt=""> -->
  <div class="banner">
   <!--  <br>
    <br> -->
    <div id="mosaic">
  <div class="container">
    <div class="row">
     <div class="col-xs-12 col-md-8 col-md-offset-2">
     <!--  <div class="col-sm-7"> -->
        <div class="lead" id="">
          <h1> Stream your music directly to your fans</h1>
         <% if user_signed_in? %>
           <% if current_user.rooms.size > 0 %>
             <%= link_to "Let's start", rooms_path, class:"btn-medium callAction_home"%>
           <% else %>
           <%= link_to "Let's start", user_session_path, class:"btn-medium callAction_home"%>
           <% end %>
           <% else %>
            <%= link_to "Let's start", user_session_path, class:"btn-medium callAction_home"%>
         <% end %>

           <p class="title2">Let your fans chat and listen to your music with you</p>
        </div>
     </div>
    </div>
  </div>
</div>

<div id="hashtags">
  <div class="container">
    <div class="row text-center">
      <div class="col-sm-4 col-xs-12">
        <div class="blok">
        <br>
          <h2>#stream</h2>
          <p class= "espaceblok">
            Stream your favorite songs, artists, albums, and playlists.
            <br>
          </p>
        </div>
      </div>
      <br>
      <div class="col-sm-4">
        <div class="blok">
          <h2>#share</h2>
          <p class= "espaceblok">
            Guarantee a full access to your live stream musical rooms

          </p>
        </div>

      </div>
      <div class="col-sm-4">
        <div class="blok">
          <h2>#live-experience</h2>
          <p class= "espaceblok">
            Receive real-time feedback from users through live chat.
          </p>
          <br>
        </div>
      </div>
    </div>
  </div>




<div class="container-fluid">
<h2>OUR TOP INFLUENCERS</h2
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-sm-offset-3 col-md-4 col-md-offset-4">
  <div class="row-stylised">
      <div class="carousel carousel-showmanymoveone slide" id="itemslider">
        <div class="carousel-inner">

          <div class="item">
            <div class="col-xs-12 col-sm-6 col-md-6 col-md-offset-3">
              <a href="#"><img src="https://static.actu.fr/uploads/2014/04/Meryl-Denis-2.jpg" class="img-responsive center-block"></a>
              <!-- <span class="badge">N°1</span> -->
              <h4 class="text-center">MERYL</h4>
              <h5 class="text-center">  96 478 Followers</h5>
            </div>
          </div>

          <div class="item active">
            <div class="col-xs-12 col-sm-6 col-md-6 col-md-offset-3">
              <a href="#"><img src="http://blog.danity.fr/wp-content/uploads/2017/02/Sans-titre-31.png" class="img-responsive center-block"></a>
            <!--   <span class="badge">N°2</span> -->
              <h4 class="text-center">ZOE</h4>
              <h5 class="text-center">  63 642 Followers</h5>
            </div>
          </div>

          <div class="item">
            <div class="col-xs-12 col-sm-6 col-md-6 col-md-offset-3">
              <a href="#"><img src="https://s-media-cache-ak0.pinimg.com/736x/dd/dc/de/dddcde7e0c249e53640f572ac620dbc2--shera-kerienski-curly-hair.jpg" class="img-responsive center-block"></a>
              <!-- <span class="badge">N°3</span> -->
              <h4 class="text-center">SHERA</h4>
              <h5 class="text-center">  59 950 Followers</h5>
            </div>
          </div>

          <div class="item">
            <div class="col-xs-12 col-sm-6 col-md-6 col-md-offset-3">
              <a href="#"><img src="http://www.envedette.ca/image/policy:1.1513417:1493231074/Lysandre-Dolbec.jpg?c=177%2C0%2C798%2C798&$p$c=73ac7a8&45" class="img-responsive center-block"></a>
             <!--  <span class="badge">N°4</span> -->
              <h4 class="text-center">BEATRICE</h4>
              <h5 class="text-center">  56 520 Followers</h5>
            </div>
          </div>


        </div>

        <div id="slider-control">
        <a class="left carousel-control" href="#itemslider" data-slide="prev"><img src="https://s12.postimg.org/uj3ffq90d/arrow_left.png" alt="Left" class="img-responsive"></a>
        <a class="right carousel-control" href="#itemslider" data-slide="next"><img src="https://s12.postimg.org/djuh0gxst/arrow_right.png" alt="Right" class="img-responsive"></a>
        <br>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="foot">
  <br>
    <h1 class="title">@weesound 2017 </h1>
    <br>
</div>

app/views/rooms/_form.html.erb
<%= simple_form_for [@room, @track] do |f| %>
  <%= f.input :title, placeholder: "Happy", required: true%>
  <%= f.input :artist , placeholder: "Pharell Williams", required: true%>
  <%= f.input :youtubeid , placeholder: "v=y6Sxv-sUYtM", required: true%>
  <%= f.button :submit, "Add song", class: "btn btn-info form-control"%>
<% end %>

app/views/rooms/index.html.erb
<div class="container min-height">
  <div class="row">
  <h1 class="title-stylized"> Hello <%= @rooms.first.user.username %> ! </h1>
  <% @rooms.each do |room| %>
    <div class="col-xs-12 col-sm-4">
      <%= link_to room_path(room) do %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path room.photo_url, width: 300, height: 200, crop: :fill %>');">
        <div class="card-category"><%= room.title %></div>
        <div class="card-description">
          <h2><%= room.description %></h2>
          <p class= "room-description"> <i><%= room.custom_message %></i> </p>
        </div>
        <div class= "card-user">
          <i class="fa fa-play-circle" aria-hidden="true"></i>
        </div>
      </div>
    <% end %>
  </div>
    <% end %>
  </div>

</div>

<div class="foot">
  <br>
    <h1 class="title">@weesound 2017 </h1>
    <br>
</div>

app/views/rooms/new.html.erb
<h1>Form to create a room</h1>

app/views/rooms/show.html.erb
<% content_for :body_id, "without-navbar" %>


<div class="container-show" style="background-image: linear-gradient(-225deg, rgba(250,250,250,0.2) 0%, rgba(250,250,250,0.2) 50%), url('<%= cl_image_path @room.photo_url%>')">
  <div class="navbar-show">
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <div class="share dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"><i class="fa fa-share-alt" aria-hidden="true"></i>
        </div>
        <ul class="dropdown-menu  navbar-weesound-dropdown-menu">
          <li>
            <!-- TODO: Make it suitable for other influencers, this works only for Meryl  -->
            <%= social_share_button_tag("Hello guys, join me for a live music session!!!   ", :url => custom_room_url(username: "weesound_meryl", room_slug: @room.slug), via: "Weesound_Meryl") %></li>
        </ul>
      </div>
      <% #if user_signed_in? %>
        <% #if @room.user == current_user %>
            <!-- <div class="logo_user"> <i class="fa fa-user-circle-o" aria-hidden="true"></i></div> -->
        <%# end %>
      <% #end %>
    </div>
    <div class="logo_wee">
      <%= link_to root_path, class: "navbar-weesound-logo" do %>
        <%= image_tag "weesound.svg" %>
      <% end %>

    </div>


    <div class="playlist-icone"><i class="fa fa-chevron-down" aria-hidden="true"></i></div>
  </div>

  <div class="container-central">
    <div class="pined-message">
      <div id= "text-width">
         <span class="quotes">"</span> <%= @room.custom_message %> <span class="quotes">"</span>  - Méryl
      </div>
      <!-- <i class="fa fa-play button_player" aria-hidden="true"></i>
      <i class="fa fa-pause button_player" aria-hidden="true"></i> -->
    </div>
    <div class="all-messages">
      <% @messages.each do |message| %>
      <%= render "messages/message", message: message %>
      <% end %>
    </div>
  </div>

  <div class="footer-player">

    <div class="chat-form">
      <% if current_user %>
        <%= simple_form_for [@room, @message], :html => {:class => 'my_form'}, remote: true do |f| %>
          <%= f.input :content, input_html: { class: 'chat-box' }, placeholder: "type your message", label: false, required: true %>
          <%= f.button :submit, "send", class: "disparition"%>
        <% end %>
      <% else %>
      <div class="signin-chat"> <%= link_to "Sign in to chat", new_user_session_path %> </div>
      <% end %>
    </div>

    <div class="player_audio">
      <div class="track-playing text-center">


      </div>

      <div class="player">
        <!-- wavesound bars -->
        <i class="fa fa-play button_player" aria-hidden="true"></i>
        <!-- <i class="fa fa-pause button_player" aria-hidden="true"></i> -->
        <div id="bars">
          <% (1..70).each do |i| %>
            <div class="bar"></div>
          <% end %>
        </div>
      </div>
    <!-- end of wavesound bars code  -->

      <div id="player" style="display:none;"></div>

    </div>
  </div>
</div>

<div class="playlist-container">
  <div class="playlist">
    <h3>The playlist</h3>
    <% @tracks.each do |track| %>
    <div class="song">
      <div class="title"><%= track.title.capitalize %></div>
      <div class="artist"><%= track.artist.capitalize %></div>
    </div>
    <% end %>
  </div>
</div>


<% content_for :after_js do %>
  <script>

  // 2. This code loads the IFrame Player API code asynchronously.
  var tag = document.createElement('script');
  tag.src = "https://www.youtube.com/iframe_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

  // 3. This function creates an <iframe> (and YouTube player)
  //    after the API code downloads.

  var player;
  function onYouTubeIframeAPIReady() {
    player = new YT.Player('player', {
      height: '360',
      width: '640',
      events: {
        'onReady': onPlayerReady,
        'onStateChange': onPlayerStateChange
      }
    });
  }


//Nos vidéos
  var videos =[];
  <% @tracks.each do |track|  %>
  videos.push('<%="#{track.youtubeid}"%>');
  <% end %>
  var index = 0;

  // 4. The API will call this function when the video player is ready.
  function onPlayerReady(event) {
    event.target.cueVideoById({
    <% if  @room.user == current_user %>
      videoId: videos[index],
    <% else %>
      videoId: '<%= "#{@room.current_track }"%>',
      startSeconds: <%= @room.current_track_time  %> +4.89,
    <% end %>
    });
    event.target.playVideo();
    if (index == 0){
      index++;
    }

     // Update the controls on load
    // updateTimerDisplay();
    // updateProgressBar();
  }

  // setInterval(function () {
  //   updateProgressBar();
  //   // updateTimerDisplay();
  // }, 1000);

// function updateTimerDisplay(){
// // Update current time text display.
// $('#current-time').text(formatTime( player.getCurrentTime() ));
// $('#duration').text(formatTime( player.getDuration() ));
// }


  // 5. The API calls this function when the player's state changes.
  //    The function indicates that when playing a video (state=1),
  //    the player should play for six seconds and then stop.

  function onPlayerStateChange(event) {
    if (event.data === YT.PlayerState.ENDED) {
      console.log(index);
      if (index <= videos.length - 1) {

        event.target.loadVideoById({
          videoId: videos[index],
        });
        index++;
      }
    }
  }

  // 1. Code Roselyne pour le play, le pause et la progress bar
  const play = document.querySelector(".fa-play");
  // const pause = document.querySelector(".fa-pause");
  // const progress = document.querySelector("#progress-bar");
  function playMusic (){
    player.playVideo();
  };
 // function pauseMusic (){
 //    player.pauseVideo();
 //  };

  // function updateProgressBar(){
  //   if (typeof player.getCurrentTime() != 'undefined' && typeof player.getDuration() != 'undefined' && player.getCurrentTime() != 0 && player.getDuration() != 0 ){
  //     progress.value = ((player.getCurrentTime() / player.getDuration()) * 100);
  //  }
  // };

  play.addEventListener("click", playMusic);
  // pause.addEventListener("click", pauseMusic);



//2- code elo drop down playlist
  var chevron_down = document.querySelector(".fa-chevron-down");
  var playlist = document.querySelector('.playlist-container');
  var playerAudio = document.querySelector('.player_audio');

  chevron_down.addEventListener('click', down);
  playerAudio.addEventListener('click', up);


  function down() {
  playlist.style.top = '0px';
};

  function up() {
  playlist.style.top = '-1045px';
};

var objDiv = document.querySelector(".all-messages");
objDiv.scrollTop = objDiv.scrollHeight;


//3- Code Fabienne pour le stream
const updateTrack = (event) => {

    $.rails.ajax({
      url: '<%= room_path(@room) %>',
      type: "PATCH",
      data: {
        room: { current_track: player.getVideoUrl(), current_track_time: player.getCurrentTime(), current_track_title: player.getVideoData().title }
      }
    })
  }


  <% if user_signed_in? && @room.user == current_user %>
    setInterval(updateTrack, 1000);
  <% end %>

// 4 - afficher le current track

 function updateTitle(){
  var myTitle = document.querySelector(".track-playing");
  let title = player.getVideoData().title;
  myTitle.innerText = title.substring(0, 43) + (title.length > 44 ? '...' : '');
  };

setInterval(function(){
  updateTitle();
  }, 2000);


// 5- chat messages
    App['room_<%= @room.id %>'] = App.cable.subscriptions.create({channel: 'RoomsChannel', room_id: <%= @room.id %>}, {
      received: function(data) {
        // selectionner le messages container
        const messagesContainer = document.querySelector(".all-messages");
        // insertAdjacentHTML beforeend lemessage
        messagesContainer.insertAdjacentHTML("beforeend", data.message_partial);
        const messages = document.querySelectorAll('.message');
        // if (messages.length > 3) {
        //   messages[0].remove();
        // }
        var objDiv = document.querySelector(".all-messages");
        objDiv.scrollTop = objDiv.scrollHeight;

        <% if user_signed_in? %>
          if(data.current_user_id === <%= current_user.id %>) {
            // si le current user est celui qui a créé le message
            const input = document.querySelector("#message_content");
            input.value = '';
          }
        <% end %>
      }
    });
  </script>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="navbar navbar-default navbar-fixed-bottom" >
  <div class="container">
        <div class="footer-links">
          <a href="#"><i class="fa fa-github"></i> Players place </a>
        </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-weesound">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-weesound-brand" do %>
    <%= image_tag "weesound.svg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
  <% if user_signed_in? %>
          <% if current_user.rooms.size > 0 %>
            <%= link_to "My rooms", rooms_path %>
            <%= link_to "Log out",  destroy_user_session_path, :method => :delete %>
            <% else %>
            <%= link_to "Log out",  destroy_user_session_path, :method => :delete %>
          <% end%>
        <% else %>
            <a href="/users/sign_in">Log in</a>
        <% end %>
    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <p class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"> </p>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>
<!-- correct navbar  -->
  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
         <% if user_signed_in? %>
          <% if current_user.rooms.size > 0 %>
            <li><%= link_to "My rooms", rooms_path %></li>
            <li><%= link_to "Log out",  destroy_user_session_path, :method => :delete %></li>
            <% else %>
            <%= link_to "Log out",  destroy_user_session_path, :method => :delete %>
          <% end%>
        <% else %>
            <a href="/users/sign_in">Log in</a>
        <% end %>
      </ul>
    </div>
  </div>
</div>